#|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|#
#|            OpenSC            |#
#|                              |#
#|         Configuration        |#
#|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|#

#|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|#
#Welcome to OpenSC, or OpenStaffChat, and thank you for downloading my plugin.
#Documentation available at https://github.com/imskyyc/openSC

#|~~~~~~~~~~ Credits ~~~~~~~~~~~|#
#Thanks to @KuramaStone on the Spigot forums for the config.yml parser

